# .github/workflows/docker-publish.yml

name: 手动发布 Docker 镜像 (带版本号)

on:
  # 允许手动触发工作流
  workflow_dispatch:
    # 定义手动触发时需要输入的参数
    inputs:
      version:
        # 参数描述，会显示在 GitHub 页面上
        description: '请输入版本号 (例如: 1.0.0)'
        # 这是一个必填参数
        required: true

jobs:
  build-and-push:
    name: 构建并推送 Docker 镜像
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 第 2 步：登录到 Docker Hub
      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 第 3 步：为 Docker 镜像提取元数据和标签
      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          # --- 您的建议已采纳 ---
          # 自动使用 DOCKERHUB_USERNAME 这个 Secret 来拼接镜像名称
          images: ${{ secrets.DOCKERHUB_USERNAME }}/doris-mcp-server
          tags: |
            type=raw,value=${{ github.event.inputs.version }}
            type=raw,value=latest

      # 第 4 步：构建并推送到 Docker Hub
      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}