# .github/workflows/docker-publish.yml

name: 手动发布 Docker 镜像

on:
  workflow_dispatch:
    inputs:
      version:
        description: '请输入版本号 (例如: 1.0.0)'
        required: true

jobs:
  build-and-push:
    name: 构建并推送 Docker 镜像
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: akyakya/doris-mcp-server
          tags: |
            type=raw,value=${{ github.event.inputs.version }}
            type=raw,value=latest

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
